TRANSLATION_LANGUAGES = [
    ("kw", "Cornish"),
    ("gv", "Manx"),
    ("br", "Breton"),
    ("iu", "Inuktitut"),
    ("kl", "Kalaallisut"),
    ("rom", "Romani"),
    ("oc", "Occitan"),
    ("lad", "Ladino"),
    ("se", "Northern Sami"),
    ("hsb", "Upper Sorbian"),
    ("csb", "Kashubian"),
    ("zza", "Zazaki"),
    ("cv", "Chuvash"),
    ("liv", "Livonian"),
    ("tsd", "Tsakonian"),
    ("srn", "Saramaccan"),
    ("bi", "Bislama"),
]
