# Generated by Django 5.1.7 on 2025-03-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("skills", models.TextField()),
                ("projects", models.TextField()),
                ("contacts", models.TextField()),
            ],
        ),
    ]
