# Generated by Django 5.1.7 on 2025-03-31 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=200)),
                ("query_string", models.TextField(blank=True)),
                ("remote_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user", models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
